# Generated by Django 3.0.7 on 2020-07-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200726_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
